### ISSUE TITLE
Building the 32-bit VM fails

### ISSUE THREAD

**Issue by heistermann** [openradar/oss_weather_radar_vm#29]
I opened an issue here regarding the problem the building the 32-bit VM.

Based on the current revision, I was not able to build the 32-bit VM from source due to an unspecific time-out error after `default: SSH auth method: private key`. 

I searched a little and tried [this solution](https://github.com/mitchellh/vagrant/issues/3860#issuecomment-167664778), but only step 1 (require). This means that I modified the 32-bit section of the `vagrantfile` to look like:

```bash
  # A 32-bit VM can also be create, comment out the above block and
  # uncomment this block
  config.vm.box = "trusty32"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-i386-vagrant-disk1.box"
  # configure VM instance
  config.vm.provider "virtualbox" do |vb|
	vb.customize ["modifyvm", :id, "--hwvirtex", "off"]
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    ### Change network card to PCnet-FAST III
    # For NAT adapter
    vb.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
    # For host-only adapter
    vb.customize ["modifyvm", :id, "--nictype2", "Am79C973"]
  end
```

This way, I was able to build the VM from source. However, it seems that the notebook interaction does not work. For example, Daniel reported the following error (and I could reproduce it):

![overflowerror](https://cloud.githubusercontent.com/assets/7724047/18862963/4e9b180c-848f-11e6-84c9-c541986e8ba7.png)

Of course, I woudn't know whether this error was caused by the way I had edited the `vagrant` file.

Does somebody have an idea? Could somebody maybe try to build the 32-bit version from source with the current revision? I am still getting the time out.

**Comment by heistermann** [comment]
I am still stuck... trusty64 works fine, but building with trusty32 times out, probably due to some networking/authentication issues.

As time is becoming short, it might be good if someone else could try to build the 32bit image.

**Comment by heistermann** [comment]
Oh, and I forgot to mention that in case I build the 32-bit VM based on the modifications outlined above, all inline plots in the jupyter notebooks will fail - so this does not only affect the pyart2baltrad stuff.

**Comment by jjhelmus** [comment]
I'm seeing the same OverflowError when I tried to run the 32-bit VM after building from source.  I did not need make any modifications for ssh to work but this might depend on the OS/Vagrant/VirtualBox setup.  

I think the issue may be coming from the RadX install which is including 64-bit shared libraries which may be conflicting with the system installed libraries.

**Comment by heistermann** [comment]
Sounds interesting! Did you already try to uncomment the Radx provisioning?

**Comment by jjhelmus** [comment]
> Did you already try to uncomment the Radx provisioning?

I tried but I am still seeing the issue, looks like my guess was incorrect.  I'm going to try commenting out additional provisioning steps to figure out what step is causing the issue.

**Comment by jjhelmus** [comment]
Commenting out the BALTRAD install results in VM that does have the issue when creating plots in IPython notebooks.

**Comment by heistermann** [comment]
Commenting out all provisioning in the section `provision machine with open source radar software` (except `install_scipy_stack.sh`) "solves" the issue. This means I can create a new notebook and successfully execute

```python
%pylab inline
plot(np.arange(10), np.arange(10))
```

So it in fact has to be one of the radare packages causing the trouble?

**Comment by heistermann** [comment]
I ran two different configurations: 

1. Provisioning only Py-ART and wradlib
2. Provisioning only wradlib

The `OverflowError` only occurs with the first configuration. I have not narrowed down what might cause the issue inside `install_pyart.sh` - could be one of 
- [ ] libfontconfig1
- [ ] python-mpltoolkits.basemap
- [ ] gfortran

**Comment by jjhelmus** [comment]
What about configuring only Py-ART?  Does that cause the `OverflowError`?

**Comment by heistermann** [comment]
Sorry, please disregard my above comments... I thought that running

```python
%pylab inline
plot(np.arange(10), np.arange(10))
```

successfully would be a sign that the issue went away. But when I install wradlib only, the above code runs successfully, but the wradlib notebooks with inline plotting still break with the `OverflowError`. 

So I would have to see again if I can somehow reproduce the error if I only run `install_scipy_stack.sh` and not any of the radar packages. Sorry for the confusion...just reflects my mental state.

**Comment by heistermann** [comment]
zeromq/pyzmq#533 appears to be a similar issue, but it is not related to IPython...anything we can learn from that - I can't.

**Comment by jjhelmus** [comment]
@heistermann I'm seeing the same issue but am having issue trying to make a minimal example that does not make use of wradlb or Py-ART.

**Comment by heistermann** [comment]
Ok, here's another one...

From the provisioning section, I only run `install_scipy_stack.sh`.

Then I create a notebook and run

```python
%pylab inline
x = np.arange(100)
y = np.arange(100)
x,y = np.meshgrid(x,y)
z = np.random.normal(0,1,(100,100))
pcolormesh(x,y,z)
```

That runs fine.

But if I increase the size of the arrays, e.g. like this

```python
x = np.arange(1000)
y = np.arange(1000)
x,y = np.meshgrid(x,y)
z = np.random.normal(0,1,(1000,1000))
pcolormesh(x,y,z)
```

I get the same `OverflowError: can't convert negative value to size_t`.

So this is where we stand...issue is not caused by the radar packages. But I still don't understand. Any ideas?

**Comment by heistermann** [comment]
@jjhelmus Sorry, I need to leave for today. Thank you so much for yourt support - I hope we'll track this down.

**Comment by jjhelmus** [comment]
Upgrading zmq to the latest version (15.4.0) seems to fix the issue.  This can be done by using the following line `sudo pip install --upgrade zmq`.

**Comment by jjhelmus** [comment]
I'll submit the PR shortly with a change to the scipy provisioning script that I think will fix the issue.  Thanks @heistermann for help tracking this down.
