### ISSUE TITLE
Py-ART notebooks fail because sample data is not found

### ISSUE THREAD

**Issue by heistermann** [openradar/oss_weather_radar_vm#42]
Py-ART notebooks do not work yet because the sample data is not found (either not installed or wrong path/file names?) - @zssherman and @scollis can you confirm that or are you already aware?

**Comment by zssherman** [comment]
@heistermann So it seems that pyart's data get downloaded when I get data script is ran in the pyart short course repository. I believe in the pass, the user has to run it, but I can change it so that the data is downloaded during the creation of the virtual environment.

**Comment by heistermann** [comment]
Ah, I see. I'd say it is up to you - if you want to keep it that way, it is fine with me. In that case, the users will download the data during the course. Should I close the issue?

**Comment by zssherman** [comment]
Maybe leave it open for now. I think I'll probably add it to the virtual environment.

**Comment by zssherman** [comment]
@heistermann So it seems that in the install_pyart_notebooks.sh script, the installation of data is there but commented out. Putting the code back in would increase the VirtualBox size by 1 GB.

**Comment by zssherman** [comment]
Fixed in #44 closing.
