### ISSUE TITLE
Making the vagrant provisioning more robust

### ISSUE THREAD

**Issue by heistermann** [openradar/oss_weather_radar_vm#9]
A common experience with building the VM from the vagrant code is erratic failure. Sometimes e.g. apt-get commands will fail because the package provider is temporarily unavailable, and this will break the built process. 

Right now, my personal solution is to repeatedly run vagrant provision until I finally manage to run through the entire built process. This is obviously ugly. Does anyone have an idea how to make this process more robust?

**Comment by DanielMichelson** [comment]
I haven't experienced such problems more than maybe once, so I guess I'm
fortunate.
Nevertheless, I wonder whether the setting of config.vm.box_url in
Vagrantfile makes a big difference.
If apt-get installs from a locally mounted .box, as Jonathan has shown us,
then may this problem would go away.
Problem is that you first have to download something big and bulky, so it
wouldn't be an elegant solution.

best, >-D


On Mon, Mar 30, 2015 at 11:38 AM, Maik Heistermann <notifications@github.com

**Comment by jjhelmus** [comment]
There are a number of vagrant plug-in which will cache apt-get packages (and certain other packages) which I use to make the provisioning more reliable.  The Vagrant file is set up to use the [vagrant-cachier](http://fgrehm.viewdocs.io/vagrant-cachier) plugin which seem to work well.  I also would echo @DanielMichelson comment that using pre-downloaded .box file is recommended.  I think vagrant may cache this file locally but am not certain.
